CREATE DATABASE /*!32312 IF NOT EXISTS*/ `ixias` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `ixias`;

CREATE TABLE `test` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `local_date` DATE NOT NULL,
  `local_time` TIME NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
